ServerName localhost

<Files "migrar.controller.php">
    Require all denied
</Files>

<Files "migrar_50_75.controller.php">
    Require all denied
</Files>

<Directory "/var/www/html">
    AllowOverride All
</Directory>
